import Head from "next/head";
import ProductPage from "@/src/Screens/ProductPage";
export default function Product() {
  return (
    <section>
      <Head>
        <title>Blinds</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ProductPage />
    </section>
  );
}
