import Head from "next/head";
import ProductDetails from "@/src/Screens/ProductPage/ProductDetails";

export default function ProductDetail() {
  return (
    <section>
      <Head>
        <title>Blinds</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ProductDetails />
    </section>
  );
}
